backend:
  name: git-gateway # 通过你的 GitHub 授权登录
  branch: main

media_folder: "images" # 图片上传存放的文件夹
public_folder: "/images"

collections:
  - name: "blog"
    label: "博客文章 (Blogs)"
    folder: "content" # 对应你刚才建的文件夹
    create: true
    fields:
      - {label: "文章标题", name: "title", widget: "string"}
      - {label: "发布日期", name: "date", widget: "datetime"}
      - {label: "正文内容", name: "body", widget: "markdown"}